### ISSUE TITLE
codegen cannot use select fields

### ISSUE THREAD

**Issue by dareksob** [microsoft/playwright-cli#80]
Cannot select a select option item.

Try it with:
playwright-cli codegen https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select

**Comment by dschuessler** [comment]
Same problem. Full command is: `npx playwright-cli codegen https://www.globalsqa.com/demo-site/select-dropdown-menu/`

playwright-cli 0.5.2
node 14.10.1

**Comment by mxschmitt** [comment]
Hi @dareksob @dschuessler thanks for reporting that issue. It should be fixed on the development version which you can use with "npm install playwright-cli@next".

**Comment by dschuessler** [comment]
I don't believe the problem is really solved. One can make selections now, but the generated code produces multiple Typescript errors.

![Bildschirmfoto 2020-09-28 um 14 07 49](https://user-images.githubusercontent.com/5774545/94430412-2a378000-0194-11eb-93c8-0d013b4b5787.png)

![Bildschirmfoto 2020-09-28 um 14 06 50](https://user-images.githubusercontent.com/5774545/94430417-2c99da00-0194-11eb-9257-479679255282.png)

**Comment by dareksob** [comment]
Thanks @mxschmitt,
looks better, but like @dschuessler wrote, the generator generate wrong selection pattern. The problem is the double slashes \\.

**Comment by rmallof** [comment]
Hi @mxschmitt, thanks for looking into this

I'm testing the latest release and the master version; none of them allow me to properly interact with select fields like https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select - I'm unable to choose any option

**Comment by rmallof** [comment]
@pavelfeldman it's working with FireFox and WebKit, though
